// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

public interface CoinIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.CoinIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
   *example: "{&#92;"id&#92;":&#92;"0&#92;"}"
   *};
   * </pre>
   *
   * <code>uint64 height = 1;</code>
   * @return The height.
   */
  long getHeight();

  /**
   * <code>uint64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
