// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

public interface EstimateCoinBuyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.EstimateCoinBuyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string will_pay = 1;</code>
   * @return The willPay.
   */
  java.lang.String getWillPay();
  /**
   * <code>string will_pay = 1;</code>
   * @return The bytes for willPay.
   */
  com.google.protobuf.ByteString
      getWillPayBytes();

  /**
   * <code>string commission = 2;</code>
   * @return The commission.
   */
  java.lang.String getCommission();
  /**
   * <code>string commission = 2;</code>
   * @return The bytes for commission.
   */
  com.google.protobuf.ByteString
      getCommissionBytes();

  /**
   * <code>.api_pb.SwapFrom swap_from = 3;</code>
   * @return The enum numeric value on the wire for swapFrom.
   */
  int getSwapFromValue();
  /**
   * <code>.api_pb.SwapFrom swap_from = 3;</code>
   * @return The swapFrom.
   */
  counters.minter.grpc.client.SwapFrom getSwapFrom();
}
