// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

/**
 * Protobuf type {@code api_pb.FrozenResponse}
 */
public final class FrozenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api_pb.FrozenResponse)
    FrozenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FrozenResponse.newBuilder() to construct.
  private FrozenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FrozenResponse() {
    frozen_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FrozenResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FrozenResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              frozen_ = new java.util.ArrayList<counters.minter.grpc.client.FrozenResponse.Frozen>();
              mutable_bitField0_ |= 0x00000001;
            }
            frozen_.add(
                input.readMessage(counters.minter.grpc.client.FrozenResponse.Frozen.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        frozen_ = java.util.Collections.unmodifiableList(frozen_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            counters.minter.grpc.client.FrozenResponse.class, counters.minter.grpc.client.FrozenResponse.Builder.class);
  }

  public interface FrozenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:api_pb.FrozenResponse.Frozen)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 height = 1;</code>
     * @return The height.
     */
    long getHeight();

    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string candidate_key = 3;</code>
     * @return The candidateKey.
     */
    java.lang.String getCandidateKey();
    /**
     * <code>string candidate_key = 3;</code>
     * @return The bytes for candidateKey.
     */
    com.google.protobuf.ByteString
        getCandidateKeyBytes();

    /**
     * <code>.api_pb.Coin coin = 4;</code>
     * @return Whether the coin field is set.
     */
    boolean hasCoin();
    /**
     * <code>.api_pb.Coin coin = 4;</code>
     * @return The coin.
     */
    counters.minter.grpc.client.Coin getCoin();
    /**
     * <code>.api_pb.Coin coin = 4;</code>
     */
    counters.minter.grpc.client.CoinOrBuilder getCoinOrBuilder();

    /**
     * <code>string value = 5;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 5;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code api_pb.FrozenResponse.Frozen}
   */
  public static final class Frozen extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:api_pb.FrozenResponse.Frozen)
      FrozenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Frozen.newBuilder() to construct.
    private Frozen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Frozen() {
      address_ = "";
      candidateKey_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Frozen();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Frozen(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              height_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              candidateKey_ = s;
              break;
            }
            case 34: {
              counters.minter.grpc.client.Coin.Builder subBuilder = null;
              if (coin_ != null) {
                subBuilder = coin_.toBuilder();
              }
              coin_ = input.readMessage(counters.minter.grpc.client.Coin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coin_);
                coin_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_Frozen_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_Frozen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              counters.minter.grpc.client.FrozenResponse.Frozen.class, counters.minter.grpc.client.FrozenResponse.Frozen.Builder.class);
    }

    public static final int HEIGHT_FIELD_NUMBER = 1;
    private long height_;
    /**
     * <code>uint64 height = 1;</code>
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return height_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANDIDATE_KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object candidateKey_;
    /**
     * <code>string candidate_key = 3;</code>
     * @return The candidateKey.
     */
    @java.lang.Override
    public java.lang.String getCandidateKey() {
      java.lang.Object ref = candidateKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidateKey_ = s;
        return s;
      }
    }
    /**
     * <code>string candidate_key = 3;</code>
     * @return The bytes for candidateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCandidateKeyBytes() {
      java.lang.Object ref = candidateKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COIN_FIELD_NUMBER = 4;
    private counters.minter.grpc.client.Coin coin_;
    /**
     * <code>.api_pb.Coin coin = 4;</code>
     * @return Whether the coin field is set.
     */
    @java.lang.Override
    public boolean hasCoin() {
      return coin_ != null;
    }
    /**
     * <code>.api_pb.Coin coin = 4;</code>
     * @return The coin.
     */
    @java.lang.Override
    public counters.minter.grpc.client.Coin getCoin() {
      return coin_ == null ? counters.minter.grpc.client.Coin.getDefaultInstance() : coin_;
    }
    /**
     * <code>.api_pb.Coin coin = 4;</code>
     */
    @java.lang.Override
    public counters.minter.grpc.client.CoinOrBuilder getCoinOrBuilder() {
      return getCoin();
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 5;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (height_ != 0L) {
        output.writeUInt64(1, height_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
      }
      if (!getCandidateKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, candidateKey_);
      }
      if (coin_ != null) {
        output.writeMessage(4, getCoin());
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, height_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
      }
      if (!getCandidateKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, candidateKey_);
      }
      if (coin_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCoin());
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof counters.minter.grpc.client.FrozenResponse.Frozen)) {
        return super.equals(obj);
      }
      counters.minter.grpc.client.FrozenResponse.Frozen other = (counters.minter.grpc.client.FrozenResponse.Frozen) obj;

      if (getHeight()
          != other.getHeight()) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getCandidateKey()
          .equals(other.getCandidateKey())) return false;
      if (hasCoin() != other.hasCoin()) return false;
      if (hasCoin()) {
        if (!getCoin()
            .equals(other.getCoin())) return false;
      }
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + CANDIDATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateKey().hashCode();
      if (hasCoin()) {
        hash = (37 * hash) + COIN_FIELD_NUMBER;
        hash = (53 * hash) + getCoin().hashCode();
      }
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static counters.minter.grpc.client.FrozenResponse.Frozen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(counters.minter.grpc.client.FrozenResponse.Frozen prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code api_pb.FrozenResponse.Frozen}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:api_pb.FrozenResponse.Frozen)
        counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_Frozen_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_Frozen_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                counters.minter.grpc.client.FrozenResponse.Frozen.class, counters.minter.grpc.client.FrozenResponse.Frozen.Builder.class);
      }

      // Construct using counters.minter.grpc.client.FrozenResponse.Frozen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        height_ = 0L;

        address_ = "";

        candidateKey_ = "";

        if (coinBuilder_ == null) {
          coin_ = null;
        } else {
          coin_ = null;
          coinBuilder_ = null;
        }
        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_Frozen_descriptor;
      }

      @java.lang.Override
      public counters.minter.grpc.client.FrozenResponse.Frozen getDefaultInstanceForType() {
        return counters.minter.grpc.client.FrozenResponse.Frozen.getDefaultInstance();
      }

      @java.lang.Override
      public counters.minter.grpc.client.FrozenResponse.Frozen build() {
        counters.minter.grpc.client.FrozenResponse.Frozen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public counters.minter.grpc.client.FrozenResponse.Frozen buildPartial() {
        counters.minter.grpc.client.FrozenResponse.Frozen result = new counters.minter.grpc.client.FrozenResponse.Frozen(this);
        result.height_ = height_;
        result.address_ = address_;
        result.candidateKey_ = candidateKey_;
        if (coinBuilder_ == null) {
          result.coin_ = coin_;
        } else {
          result.coin_ = coinBuilder_.build();
        }
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof counters.minter.grpc.client.FrozenResponse.Frozen) {
          return mergeFrom((counters.minter.grpc.client.FrozenResponse.Frozen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(counters.minter.grpc.client.FrozenResponse.Frozen other) {
        if (other == counters.minter.grpc.client.FrozenResponse.Frozen.getDefaultInstance()) return this;
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getCandidateKey().isEmpty()) {
          candidateKey_ = other.candidateKey_;
          onChanged();
        }
        if (other.hasCoin()) {
          mergeCoin(other.getCoin());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        counters.minter.grpc.client.FrozenResponse.Frozen parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (counters.minter.grpc.client.FrozenResponse.Frozen) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long height_ ;
      /**
       * <code>uint64 height = 1;</code>
       * @return The height.
       */
      @java.lang.Override
      public long getHeight() {
        return height_;
      }
      /**
       * <code>uint64 height = 1;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 height = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 2;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 2;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 2;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 2;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object candidateKey_ = "";
      /**
       * <code>string candidate_key = 3;</code>
       * @return The candidateKey.
       */
      public java.lang.String getCandidateKey() {
        java.lang.Object ref = candidateKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          candidateKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string candidate_key = 3;</code>
       * @return The bytes for candidateKey.
       */
      public com.google.protobuf.ByteString
          getCandidateKeyBytes() {
        java.lang.Object ref = candidateKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidateKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string candidate_key = 3;</code>
       * @param value The candidateKey to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        candidateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string candidate_key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidateKey() {
        
        candidateKey_ = getDefaultInstance().getCandidateKey();
        onChanged();
        return this;
      }
      /**
       * <code>string candidate_key = 3;</code>
       * @param value The bytes for candidateKey to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        candidateKey_ = value;
        onChanged();
        return this;
      }

      private counters.minter.grpc.client.Coin coin_;
      private com.google.protobuf.SingleFieldBuilderV3<
          counters.minter.grpc.client.Coin, counters.minter.grpc.client.Coin.Builder, counters.minter.grpc.client.CoinOrBuilder> coinBuilder_;
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       * @return Whether the coin field is set.
       */
      public boolean hasCoin() {
        return coinBuilder_ != null || coin_ != null;
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       * @return The coin.
       */
      public counters.minter.grpc.client.Coin getCoin() {
        if (coinBuilder_ == null) {
          return coin_ == null ? counters.minter.grpc.client.Coin.getDefaultInstance() : coin_;
        } else {
          return coinBuilder_.getMessage();
        }
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      public Builder setCoin(counters.minter.grpc.client.Coin value) {
        if (coinBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coin_ = value;
          onChanged();
        } else {
          coinBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      public Builder setCoin(
          counters.minter.grpc.client.Coin.Builder builderForValue) {
        if (coinBuilder_ == null) {
          coin_ = builderForValue.build();
          onChanged();
        } else {
          coinBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      public Builder mergeCoin(counters.minter.grpc.client.Coin value) {
        if (coinBuilder_ == null) {
          if (coin_ != null) {
            coin_ =
              counters.minter.grpc.client.Coin.newBuilder(coin_).mergeFrom(value).buildPartial();
          } else {
            coin_ = value;
          }
          onChanged();
        } else {
          coinBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      public Builder clearCoin() {
        if (coinBuilder_ == null) {
          coin_ = null;
          onChanged();
        } else {
          coin_ = null;
          coinBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      public counters.minter.grpc.client.Coin.Builder getCoinBuilder() {
        
        onChanged();
        return getCoinFieldBuilder().getBuilder();
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      public counters.minter.grpc.client.CoinOrBuilder getCoinOrBuilder() {
        if (coinBuilder_ != null) {
          return coinBuilder_.getMessageOrBuilder();
        } else {
          return coin_ == null ?
              counters.minter.grpc.client.Coin.getDefaultInstance() : coin_;
        }
      }
      /**
       * <code>.api_pb.Coin coin = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          counters.minter.grpc.client.Coin, counters.minter.grpc.client.Coin.Builder, counters.minter.grpc.client.CoinOrBuilder> 
          getCoinFieldBuilder() {
        if (coinBuilder_ == null) {
          coinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              counters.minter.grpc.client.Coin, counters.minter.grpc.client.Coin.Builder, counters.minter.grpc.client.CoinOrBuilder>(
                  getCoin(),
                  getParentForChildren(),
                  isClean());
          coin_ = null;
        }
        return coinBuilder_;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 5;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 5;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 5;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 5;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:api_pb.FrozenResponse.Frozen)
    }

    // @@protoc_insertion_point(class_scope:api_pb.FrozenResponse.Frozen)
    private static final counters.minter.grpc.client.FrozenResponse.Frozen DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new counters.minter.grpc.client.FrozenResponse.Frozen();
    }

    public static counters.minter.grpc.client.FrozenResponse.Frozen getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Frozen>
        PARSER = new com.google.protobuf.AbstractParser<Frozen>() {
      @java.lang.Override
      public Frozen parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frozen(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Frozen> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Frozen> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public counters.minter.grpc.client.FrozenResponse.Frozen getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int FROZEN_FIELD_NUMBER = 1;
  private java.util.List<counters.minter.grpc.client.FrozenResponse.Frozen> frozen_;
  /**
   * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
   */
  @java.lang.Override
  public java.util.List<counters.minter.grpc.client.FrozenResponse.Frozen> getFrozenList() {
    return frozen_;
  }
  /**
   * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder> 
      getFrozenOrBuilderList() {
    return frozen_;
  }
  /**
   * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
   */
  @java.lang.Override
  public int getFrozenCount() {
    return frozen_.size();
  }
  /**
   * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
   */
  @java.lang.Override
  public counters.minter.grpc.client.FrozenResponse.Frozen getFrozen(int index) {
    return frozen_.get(index);
  }
  /**
   * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
   */
  @java.lang.Override
  public counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder getFrozenOrBuilder(
      int index) {
    return frozen_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < frozen_.size(); i++) {
      output.writeMessage(1, frozen_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < frozen_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, frozen_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof counters.minter.grpc.client.FrozenResponse)) {
      return super.equals(obj);
    }
    counters.minter.grpc.client.FrozenResponse other = (counters.minter.grpc.client.FrozenResponse) obj;

    if (!getFrozenList()
        .equals(other.getFrozenList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFrozenCount() > 0) {
      hash = (37 * hash) + FROZEN_FIELD_NUMBER;
      hash = (53 * hash) + getFrozenList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static counters.minter.grpc.client.FrozenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static counters.minter.grpc.client.FrozenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static counters.minter.grpc.client.FrozenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(counters.minter.grpc.client.FrozenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api_pb.FrozenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api_pb.FrozenResponse)
      counters.minter.grpc.client.FrozenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              counters.minter.grpc.client.FrozenResponse.class, counters.minter.grpc.client.FrozenResponse.Builder.class);
    }

    // Construct using counters.minter.grpc.client.FrozenResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFrozenFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (frozenBuilder_ == null) {
        frozen_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        frozenBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return counters.minter.grpc.client.Resources.internal_static_api_pb_FrozenResponse_descriptor;
    }

    @java.lang.Override
    public counters.minter.grpc.client.FrozenResponse getDefaultInstanceForType() {
      return counters.minter.grpc.client.FrozenResponse.getDefaultInstance();
    }

    @java.lang.Override
    public counters.minter.grpc.client.FrozenResponse build() {
      counters.minter.grpc.client.FrozenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public counters.minter.grpc.client.FrozenResponse buildPartial() {
      counters.minter.grpc.client.FrozenResponse result = new counters.minter.grpc.client.FrozenResponse(this);
      int from_bitField0_ = bitField0_;
      if (frozenBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          frozen_ = java.util.Collections.unmodifiableList(frozen_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.frozen_ = frozen_;
      } else {
        result.frozen_ = frozenBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof counters.minter.grpc.client.FrozenResponse) {
        return mergeFrom((counters.minter.grpc.client.FrozenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(counters.minter.grpc.client.FrozenResponse other) {
      if (other == counters.minter.grpc.client.FrozenResponse.getDefaultInstance()) return this;
      if (frozenBuilder_ == null) {
        if (!other.frozen_.isEmpty()) {
          if (frozen_.isEmpty()) {
            frozen_ = other.frozen_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFrozenIsMutable();
            frozen_.addAll(other.frozen_);
          }
          onChanged();
        }
      } else {
        if (!other.frozen_.isEmpty()) {
          if (frozenBuilder_.isEmpty()) {
            frozenBuilder_.dispose();
            frozenBuilder_ = null;
            frozen_ = other.frozen_;
            bitField0_ = (bitField0_ & ~0x00000001);
            frozenBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFrozenFieldBuilder() : null;
          } else {
            frozenBuilder_.addAllMessages(other.frozen_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      counters.minter.grpc.client.FrozenResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (counters.minter.grpc.client.FrozenResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<counters.minter.grpc.client.FrozenResponse.Frozen> frozen_ =
      java.util.Collections.emptyList();
    private void ensureFrozenIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        frozen_ = new java.util.ArrayList<counters.minter.grpc.client.FrozenResponse.Frozen>(frozen_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        counters.minter.grpc.client.FrozenResponse.Frozen, counters.minter.grpc.client.FrozenResponse.Frozen.Builder, counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder> frozenBuilder_;

    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public java.util.List<counters.minter.grpc.client.FrozenResponse.Frozen> getFrozenList() {
      if (frozenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(frozen_);
      } else {
        return frozenBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public int getFrozenCount() {
      if (frozenBuilder_ == null) {
        return frozen_.size();
      } else {
        return frozenBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public counters.minter.grpc.client.FrozenResponse.Frozen getFrozen(int index) {
      if (frozenBuilder_ == null) {
        return frozen_.get(index);
      } else {
        return frozenBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder setFrozen(
        int index, counters.minter.grpc.client.FrozenResponse.Frozen value) {
      if (frozenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFrozenIsMutable();
        frozen_.set(index, value);
        onChanged();
      } else {
        frozenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder setFrozen(
        int index, counters.minter.grpc.client.FrozenResponse.Frozen.Builder builderForValue) {
      if (frozenBuilder_ == null) {
        ensureFrozenIsMutable();
        frozen_.set(index, builderForValue.build());
        onChanged();
      } else {
        frozenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder addFrozen(counters.minter.grpc.client.FrozenResponse.Frozen value) {
      if (frozenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFrozenIsMutable();
        frozen_.add(value);
        onChanged();
      } else {
        frozenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder addFrozen(
        int index, counters.minter.grpc.client.FrozenResponse.Frozen value) {
      if (frozenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFrozenIsMutable();
        frozen_.add(index, value);
        onChanged();
      } else {
        frozenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder addFrozen(
        counters.minter.grpc.client.FrozenResponse.Frozen.Builder builderForValue) {
      if (frozenBuilder_ == null) {
        ensureFrozenIsMutable();
        frozen_.add(builderForValue.build());
        onChanged();
      } else {
        frozenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder addFrozen(
        int index, counters.minter.grpc.client.FrozenResponse.Frozen.Builder builderForValue) {
      if (frozenBuilder_ == null) {
        ensureFrozenIsMutable();
        frozen_.add(index, builderForValue.build());
        onChanged();
      } else {
        frozenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder addAllFrozen(
        java.lang.Iterable<? extends counters.minter.grpc.client.FrozenResponse.Frozen> values) {
      if (frozenBuilder_ == null) {
        ensureFrozenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, frozen_);
        onChanged();
      } else {
        frozenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder clearFrozen() {
      if (frozenBuilder_ == null) {
        frozen_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        frozenBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public Builder removeFrozen(int index) {
      if (frozenBuilder_ == null) {
        ensureFrozenIsMutable();
        frozen_.remove(index);
        onChanged();
      } else {
        frozenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public counters.minter.grpc.client.FrozenResponse.Frozen.Builder getFrozenBuilder(
        int index) {
      return getFrozenFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder getFrozenOrBuilder(
        int index) {
      if (frozenBuilder_ == null) {
        return frozen_.get(index);  } else {
        return frozenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public java.util.List<? extends counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder> 
         getFrozenOrBuilderList() {
      if (frozenBuilder_ != null) {
        return frozenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(frozen_);
      }
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public counters.minter.grpc.client.FrozenResponse.Frozen.Builder addFrozenBuilder() {
      return getFrozenFieldBuilder().addBuilder(
          counters.minter.grpc.client.FrozenResponse.Frozen.getDefaultInstance());
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public counters.minter.grpc.client.FrozenResponse.Frozen.Builder addFrozenBuilder(
        int index) {
      return getFrozenFieldBuilder().addBuilder(
          index, counters.minter.grpc.client.FrozenResponse.Frozen.getDefaultInstance());
    }
    /**
     * <code>repeated .api_pb.FrozenResponse.Frozen frozen = 1;</code>
     */
    public java.util.List<counters.minter.grpc.client.FrozenResponse.Frozen.Builder> 
         getFrozenBuilderList() {
      return getFrozenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        counters.minter.grpc.client.FrozenResponse.Frozen, counters.minter.grpc.client.FrozenResponse.Frozen.Builder, counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder> 
        getFrozenFieldBuilder() {
      if (frozenBuilder_ == null) {
        frozenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            counters.minter.grpc.client.FrozenResponse.Frozen, counters.minter.grpc.client.FrozenResponse.Frozen.Builder, counters.minter.grpc.client.FrozenResponse.FrozenOrBuilder>(
                frozen_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        frozen_ = null;
      }
      return frozenBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api_pb.FrozenResponse)
  }

  // @@protoc_insertion_point(class_scope:api_pb.FrozenResponse)
  private static final counters.minter.grpc.client.FrozenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new counters.minter.grpc.client.FrozenResponse();
  }

  public static counters.minter.grpc.client.FrozenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FrozenResponse>
      PARSER = new com.google.protobuf.AbstractParser<FrozenResponse>() {
    @java.lang.Override
    public FrozenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FrozenResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FrozenResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FrozenResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public counters.minter.grpc.client.FrozenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

