// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

public interface MaxGasPriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.MaxGasPriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 max_gas_price = 3;</code>
   * @return The maxGasPrice.
   */
  long getMaxGasPrice();
}
