// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

public interface SendTransactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.SendTransactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tx = 1 [json_name = "tx"];</code>
   * @return The tx.
   */
  java.lang.String getTx();
  /**
   * <code>string tx = 1 [json_name = "tx"];</code>
   * @return The bytes for tx.
   */
  com.google.protobuf.ByteString
      getTxBytes();
}
