// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

public interface SwapPoolsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.SwapPoolsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 height = 1 [json_name = "height"];</code>
   * @return The height.
   */
  long getHeight();

  /**
   * <code>bool orders = 2 [json_name = "orders"];</code>
   * @return The orders.
   */
  boolean getOrders();
}
