//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmName("-initializeaddressResponse")
public inline fun addressResponse(block: counters.minter.grpc.client.AddressResponseKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.AddressResponse =
  counters.minter.grpc.client.AddressResponseKt.Dsl._create(counters.minter.grpc.client.AddressResponse.newBuilder()).apply { block() }._build()
public object AddressResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: counters.minter.grpc.client.AddressResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.AddressResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.AddressResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class BalanceProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     */
     public val balance: com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getBalanceList()
      )
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     * @param value The balance to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addBalance")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>.add(value: counters.minter.grpc.client.AddressBalance) {
      _builder.addBalance(value)
    }
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     * @param value The balance to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignBalance")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>.plusAssign(value: counters.minter.grpc.client.AddressBalance) {
      add(value)
    }
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     * @param values The balance to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllBalance")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>.addAll(values: kotlin.collections.Iterable<counters.minter.grpc.client.AddressBalance>) {
      _builder.addAllBalance(values)
    }
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     * @param values The balance to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllBalance")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>.plusAssign(values: kotlin.collections.Iterable<counters.minter.grpc.client.AddressBalance>) {
      addAll(values)
    }
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     * @param index The index to set the value at.
     * @param value The balance to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setBalance")
    public operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>.set(index: kotlin.Int, value: counters.minter.grpc.client.AddressBalance) {
      _builder.setBalance(index, value)
    }
    /**
     * <code>repeated .api_pb.AddressBalance balance = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearBalance")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, BalanceProxy>.clear() {
      _builder.clearBalance()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DelegatedProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     */
     public val delegated: com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDelegatedList()
      )
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     * @param value The delegated to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDelegated")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>.add(value: counters.minter.grpc.client.AddressDelegatedBalance) {
      _builder.addDelegated(value)
    }
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     * @param value The delegated to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDelegated")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>.plusAssign(value: counters.minter.grpc.client.AddressDelegatedBalance) {
      add(value)
    }
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     * @param values The delegated to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDelegated")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>.addAll(values: kotlin.collections.Iterable<counters.minter.grpc.client.AddressDelegatedBalance>) {
      _builder.addAllDelegated(values)
    }
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     * @param values The delegated to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDelegated")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>.plusAssign(values: kotlin.collections.Iterable<counters.minter.grpc.client.AddressDelegatedBalance>) {
      addAll(values)
    }
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     * @param index The index to set the value at.
     * @param value The delegated to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDelegated")
    public operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>.set(index: kotlin.Int, value: counters.minter.grpc.client.AddressDelegatedBalance) {
      _builder.setDelegated(index, value)
    }
    /**
     * <code>repeated .api_pb.AddressDelegatedBalance delegated = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDelegated")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressDelegatedBalance, DelegatedProxy>.clear() {
      _builder.clearDelegated()
    }


    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TotalProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     */
     public val total: com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTotalList()
      )
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     * @param value The total to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTotal")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>.add(value: counters.minter.grpc.client.AddressBalance) {
      _builder.addTotal(value)
    }
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     * @param value The total to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTotal")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>.plusAssign(value: counters.minter.grpc.client.AddressBalance) {
      add(value)
    }
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     * @param values The total to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTotal")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>.addAll(values: kotlin.collections.Iterable<counters.minter.grpc.client.AddressBalance>) {
      _builder.addAllTotal(values)
    }
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     * @param values The total to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTotal")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>.plusAssign(values: kotlin.collections.Iterable<counters.minter.grpc.client.AddressBalance>) {
      addAll(values)
    }
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     * @param index The index to set the value at.
     * @param value The total to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTotal")
    public operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>.set(index: kotlin.Int, value: counters.minter.grpc.client.AddressBalance) {
      _builder.setTotal(index, value)
    }
    /**
     * <code>repeated .api_pb.AddressBalance total = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTotal")
    public fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.AddressBalance, TotalProxy>.clear() {
      _builder.clearTotal()
    }


    /**
     * <code>uint64 transaction_count = 2;</code>
     */
    public var transactionCount: kotlin.Long
      @JvmName("getTransactionCount")
      get() = _builder.getTransactionCount()
      @JvmName("setTransactionCount")
      set(value) {
        _builder.setTransactionCount(value)
      }
    /**
     * <code>uint64 transaction_count = 2;</code>
     */
    public fun clearTransactionCount() {
      _builder.clearTransactionCount()
    }

    /**
     * <code>string bip_value = 5;</code>
     */
    public var bipValue: kotlin.String
      @JvmName("getBipValue")
      get() = _builder.getBipValue()
      @JvmName("setBipValue")
      set(value) {
        _builder.setBipValue(value)
      }
    /**
     * <code>string bip_value = 5;</code>
     */
    public fun clearBipValue() {
      _builder.clearBipValue()
    }

    /**
     * <code>uint64 locked_stake_until_block = 7;</code>
     */
    public var lockedStakeUntilBlock: kotlin.Long
      @JvmName("getLockedStakeUntilBlock")
      get() = _builder.getLockedStakeUntilBlock()
      @JvmName("setLockedStakeUntilBlock")
      set(value) {
        _builder.setLockedStakeUntilBlock(value)
      }
    /**
     * <code>uint64 locked_stake_until_block = 7;</code>
     */
    public fun clearLockedStakeUntilBlock() {
      _builder.clearLockedStakeUntilBlock()
    }

    /**
     * <code>.api_pb.Multisig multisig = 6;</code>
     */
    public var multisig: counters.minter.grpc.client.Multisig
      @JvmName("getMultisig")
      get() = _builder.getMultisig()
      @JvmName("setMultisig")
      set(value) {
        _builder.setMultisig(value)
      }
    /**
     * <code>.api_pb.Multisig multisig = 6;</code>
     */
    public fun clearMultisig() {
      _builder.clearMultisig()
    }
    /**
     * <code>.api_pb.Multisig multisig = 6;</code>
     * @return Whether the multisig field is set.
     */
    public fun hasMultisig(): kotlin.Boolean {
      return _builder.hasMultisig()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun counters.minter.grpc.client.AddressResponse.copy(block: counters.minter.grpc.client.AddressResponseKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.AddressResponse =
  counters.minter.grpc.client.AddressResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val counters.minter.grpc.client.AddressResponseOrBuilder.multisigOrNull: counters.minter.grpc.client.Multisig?
  get() = if (hasMultisig()) getMultisig() else null

