//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
inline fun coinIdRequest(block: counters.minter.grpc.client.CoinIdRequestKt.Dsl.() -> Unit): counters.minter.grpc.client.CoinIdRequest =
  counters.minter.grpc.client.CoinIdRequestKt.Dsl._create(counters.minter.grpc.client.CoinIdRequest.newBuilder()).apply { block() }._build()
object CoinIdRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: counters.minter.grpc.client.CoinIdRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.CoinIdRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.CoinIdRequest = _builder.build()

    /**
     * <pre>
     *    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
     *        example: "{&#92;"id&#92;":&#92;"0&#92;"}"
     *    };
     * </pre>
     *
     * <code>uint64 height = 1;</code>
     */
    var height: kotlin.Long
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <pre>
     *    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_schema) = {
     *        example: "{&#92;"id&#92;":&#92;"0&#92;"}"
     *    };
     * </pre>
     *
     * <code>uint64 height = 1;</code>
     */
    fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * <code>uint64 id = 2;</code>
     */
    var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>uint64 id = 2;</code>
     */
    fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun counters.minter.grpc.client.CoinIdRequest.copy(block: counters.minter.grpc.client.CoinIdRequestKt.Dsl.() -> Unit): counters.minter.grpc.client.CoinIdRequest =
  counters.minter.grpc.client.CoinIdRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
