//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
inline fun estimateCoinBuyResponse(block: counters.minter.grpc.client.EstimateCoinBuyResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.EstimateCoinBuyResponse =
  counters.minter.grpc.client.EstimateCoinBuyResponseKt.Dsl._create(counters.minter.grpc.client.EstimateCoinBuyResponse.newBuilder()).apply { block() }._build()
object EstimateCoinBuyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: counters.minter.grpc.client.EstimateCoinBuyResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.EstimateCoinBuyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.EstimateCoinBuyResponse = _builder.build()

    /**
     * <code>string will_pay = 1;</code>
     */
    var willPay: kotlin.String
      @JvmName("getWillPay")
      get() = _builder.getWillPay()
      @JvmName("setWillPay")
      set(value) {
        _builder.setWillPay(value)
      }
    /**
     * <code>string will_pay = 1;</code>
     */
    fun clearWillPay() {
      _builder.clearWillPay()
    }

    /**
     * <code>string commission = 2;</code>
     */
    var commission: kotlin.String
      @JvmName("getCommission")
      get() = _builder.getCommission()
      @JvmName("setCommission")
      set(value) {
        _builder.setCommission(value)
      }
    /**
     * <code>string commission = 2;</code>
     */
    fun clearCommission() {
      _builder.clearCommission()
    }

    /**
     * <code>.api_pb.SwapFrom swap_from = 3;</code>
     */
    var swapFrom: counters.minter.grpc.client.SwapFrom
      @JvmName("getSwapFrom")
      get() = _builder.getSwapFrom()
      @JvmName("setSwapFrom")
      set(value) {
        _builder.setSwapFrom(value)
      }
    /**
     * <code>.api_pb.SwapFrom swap_from = 3;</code>
     */
    fun clearSwapFrom() {
      _builder.clearSwapFrom()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun counters.minter.grpc.client.EstimateCoinBuyResponse.copy(block: counters.minter.grpc.client.EstimateCoinBuyResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.EstimateCoinBuyResponse =
  counters.minter.grpc.client.EstimateCoinBuyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
