//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
inline fun estimateCoinSellResponse(block: counters.minter.grpc.client.EstimateCoinSellResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.EstimateCoinSellResponse =
  counters.minter.grpc.client.EstimateCoinSellResponseKt.Dsl._create(counters.minter.grpc.client.EstimateCoinSellResponse.newBuilder()).apply { block() }._build()
object EstimateCoinSellResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: counters.minter.grpc.client.EstimateCoinSellResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.EstimateCoinSellResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.EstimateCoinSellResponse = _builder.build()

    /**
     * <code>string will_get = 1;</code>
     */
    var willGet: kotlin.String
      @JvmName("getWillGet")
      get() = _builder.getWillGet()
      @JvmName("setWillGet")
      set(value) {
        _builder.setWillGet(value)
      }
    /**
     * <code>string will_get = 1;</code>
     */
    fun clearWillGet() {
      _builder.clearWillGet()
    }

    /**
     * <code>string commission = 2;</code>
     */
    var commission: kotlin.String
      @JvmName("getCommission")
      get() = _builder.getCommission()
      @JvmName("setCommission")
      set(value) {
        _builder.setCommission(value)
      }
    /**
     * <code>string commission = 2;</code>
     */
    fun clearCommission() {
      _builder.clearCommission()
    }

    /**
     * <code>.api_pb.SwapFrom swap_from = 3;</code>
     */
    var swapFrom: counters.minter.grpc.client.SwapFrom
      @JvmName("getSwapFrom")
      get() = _builder.getSwapFrom()
      @JvmName("setSwapFrom")
      set(value) {
        _builder.setSwapFrom(value)
      }
    /**
     * <code>.api_pb.SwapFrom swap_from = 3;</code>
     */
    fun clearSwapFrom() {
      _builder.clearSwapFrom()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun counters.minter.grpc.client.EstimateCoinSellResponse.copy(block: counters.minter.grpc.client.EstimateCoinSellResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.EstimateCoinSellResponse =
  counters.minter.grpc.client.EstimateCoinSellResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
