//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
inline fun haltsResponse(block: counters.minter.grpc.client.HaltsResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.HaltsResponse =
  counters.minter.grpc.client.HaltsResponseKt.Dsl._create(counters.minter.grpc.client.HaltsResponse.newBuilder()).apply { block() }._build()
object HaltsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: counters.minter.grpc.client.HaltsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.HaltsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.HaltsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class PublicKeysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string public_keys = 1;</code>
     * @return A list containing the publicKeys.
     */
    val publicKeys: com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPublicKeysList()
      )
    /**
     * <code>repeated string public_keys = 1;</code>
     * @param value The publicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPublicKeys")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>.add(value: kotlin.String) {
      _builder.addPublicKeys(value)
    }
    /**
     * <code>repeated string public_keys = 1;</code>
     * @param value The publicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPublicKeys")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>.plusAssign(value: kotlin.String) {
      _builder.addPublicKeys(value)
    }
    /**
     * <code>repeated string public_keys = 1;</code>
     * @param values The publicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPublicKeys")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPublicKeys(values)
    }
    /**
     * <code>repeated string public_keys = 1;</code>
     * @param values The publicKeys to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPublicKeys")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllPublicKeys(values)
    }
    /**
     * <code>repeated string public_keys = 1;</code>
     * @param index The index to set the value at.
     * @param value The publicKeys to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPublicKeys")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setPublicKeys(index, value)
    }/**
     * <code>repeated string public_keys = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPublicKeys")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, PublicKeysProxy>.clear() {
      _builder.clearPublicKeys()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun counters.minter.grpc.client.HaltsResponse.copy(block: counters.minter.grpc.client.HaltsResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.HaltsResponse =
  counters.minter.grpc.client.HaltsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
