//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: data.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmName("-initializemoveStakeData")
public inline fun moveStakeData(block: counters.minter.grpc.client.MoveStakeDataKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.MoveStakeData =
  counters.minter.grpc.client.MoveStakeDataKt.Dsl._create(counters.minter.grpc.client.MoveStakeData.newBuilder()).apply { block() }._build()
public object MoveStakeDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: counters.minter.grpc.client.MoveStakeData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.MoveStakeData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.MoveStakeData = _builder.build()

    /**
     * <code>string from_pub_key = 1;</code>
     */
    public var fromPubKey: kotlin.String
      @JvmName("getFromPubKey")
      get() = _builder.getFromPubKey()
      @JvmName("setFromPubKey")
      set(value) {
        _builder.setFromPubKey(value)
      }
    /**
     * <code>string from_pub_key = 1;</code>
     */
    public fun clearFromPubKey() {
      _builder.clearFromPubKey()
    }

    /**
     * <code>string to_pub_key = 4;</code>
     */
    public var toPubKey: kotlin.String
      @JvmName("getToPubKey")
      get() = _builder.getToPubKey()
      @JvmName("setToPubKey")
      set(value) {
        _builder.setToPubKey(value)
      }
    /**
     * <code>string to_pub_key = 4;</code>
     */
    public fun clearToPubKey() {
      _builder.clearToPubKey()
    }

    /**
     * <code>.api_pb.Coin coin = 2;</code>
     */
    public var coin: counters.minter.grpc.client.Coin
      @JvmName("getCoin")
      get() = _builder.getCoin()
      @JvmName("setCoin")
      set(value) {
        _builder.setCoin(value)
      }
    /**
     * <code>.api_pb.Coin coin = 2;</code>
     */
    public fun clearCoin() {
      _builder.clearCoin()
    }
    /**
     * <code>.api_pb.Coin coin = 2;</code>
     * @return Whether the coin field is set.
     */
    public fun hasCoin(): kotlin.Boolean {
      return _builder.hasCoin()
    }

    /**
     * <code>string value = 3;</code>
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <code>string value = 3;</code>
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun counters.minter.grpc.client.MoveStakeData.copy(block: counters.minter.grpc.client.MoveStakeDataKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.MoveStakeData =
  counters.minter.grpc.client.MoveStakeDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val counters.minter.grpc.client.MoveStakeDataOrBuilder.coinOrNull: counters.minter.grpc.client.Coin?
  get() = if (hasCoin()) getCoin() else null

