//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
inline fun transactionsResponse(block: counters.minter.grpc.client.TransactionsResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.TransactionsResponse =
  counters.minter.grpc.client.TransactionsResponseKt.Dsl._create(counters.minter.grpc.client.TransactionsResponse.newBuilder()).apply { block() }._build()
object TransactionsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: counters.minter.grpc.client.TransactionsResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.TransactionsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.TransactionsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class TransactionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     */
     val transactions: com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTransactionsList()
      )
    /**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     * @param value The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTransactions")
    fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>.add(value: counters.minter.grpc.client.TransactionResponse) {
      _builder.addTransactions(value)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     * @param value The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTransactions")
    inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>.plusAssign(value: counters.minter.grpc.client.TransactionResponse) {
      add(value)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     * @param values The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTransactions")
    fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>.addAll(values: kotlin.collections.Iterable<counters.minter.grpc.client.TransactionResponse>) {
      _builder.addAllTransactions(values)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     * @param values The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTransactions")
    inline operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>.plusAssign(values: kotlin.collections.Iterable<counters.minter.grpc.client.TransactionResponse>) {
      addAll(values)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     * @param index The index to set the value at.
     * @param value The transactions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTransactions")
    operator fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>.set(index: kotlin.Int, value: counters.minter.grpc.client.TransactionResponse) {
      _builder.setTransactions(index, value)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTransactions")
    fun com.google.protobuf.kotlin.DslList<counters.minter.grpc.client.TransactionResponse, TransactionsProxy>.clear() {
      _builder.clearTransactions()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun counters.minter.grpc.client.TransactionsResponse.copy(block: counters.minter.grpc.client.TransactionsResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.TransactionsResponse =
  counters.minter.grpc.client.TransactionsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
