//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
inline fun transactionResponse(block: counters.minter.grpc.client.TransactionResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.TransactionResponse =
  counters.minter.grpc.client.TransactionResponseKt.Dsl._create(counters.minter.grpc.client.TransactionResponse.newBuilder()).apply { block() }._build()
object TransactionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    @kotlin.jvm.JvmField private val _builder: counters.minter.grpc.client.TransactionResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.TransactionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.TransactionResponse = _builder.build()

    /**
     * <code>string hash = 1;</code>
     */
    var hash: kotlin.String
      @JvmName("getHash")
      get() = _builder.getHash()
      @JvmName("setHash")
      set(value) {
        _builder.setHash(value)
      }
    /**
     * <code>string hash = 1;</code>
     */
    fun clearHash() {
      _builder.clearHash()
    }

    /**
     * <code>string raw_tx = 2;</code>
     */
    var rawTx: kotlin.String
      @JvmName("getRawTx")
      get() = _builder.getRawTx()
      @JvmName("setRawTx")
      set(value) {
        _builder.setRawTx(value)
      }
    /**
     * <code>string raw_tx = 2;</code>
     */
    fun clearRawTx() {
      _builder.clearRawTx()
    }

    /**
     * <code>uint64 height = 3;</code>
     */
    var height: kotlin.Long
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <code>uint64 height = 3;</code>
     */
    fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * <code>uint64 index = 4;</code>
     */
    var index: kotlin.Long
      @JvmName("getIndex")
      get() = _builder.getIndex()
      @JvmName("setIndex")
      set(value) {
        _builder.setIndex(value)
      }
    /**
     * <code>uint64 index = 4;</code>
     */
    fun clearIndex() {
      _builder.clearIndex()
    }

    /**
     * <code>string from = 5;</code>
     */
    var from: kotlin.String
      @JvmName("getFrom")
      get() = _builder.getFrom()
      @JvmName("setFrom")
      set(value) {
        _builder.setFrom(value)
      }
    /**
     * <code>string from = 5;</code>
     */
    fun clearFrom() {
      _builder.clearFrom()
    }

    /**
     * <code>uint64 nonce = 6;</code>
     */
    var nonce: kotlin.Long
      @JvmName("getNonce")
      get() = _builder.getNonce()
      @JvmName("setNonce")
      set(value) {
        _builder.setNonce(value)
      }
    /**
     * <code>uint64 nonce = 6;</code>
     */
    fun clearNonce() {
      _builder.clearNonce()
    }

    /**
     * <code>uint64 gas = 7;</code>
     */
    var gas: kotlin.Long
      @JvmName("getGas")
      get() = _builder.getGas()
      @JvmName("setGas")
      set(value) {
        _builder.setGas(value)
      }
    /**
     * <code>uint64 gas = 7;</code>
     */
    fun clearGas() {
      _builder.clearGas()
    }

    /**
     * <code>uint64 gas_price = 8;</code>
     */
    var gasPrice: kotlin.Long
      @JvmName("getGasPrice")
      get() = _builder.getGasPrice()
      @JvmName("setGasPrice")
      set(value) {
        _builder.setGasPrice(value)
      }
    /**
     * <code>uint64 gas_price = 8;</code>
     */
    fun clearGasPrice() {
      _builder.clearGasPrice()
    }

    /**
     * <code>.api_pb.Coin gas_coin = 9;</code>
     */
    var gasCoin: counters.minter.grpc.client.Coin
      @JvmName("getGasCoin")
      get() = _builder.getGasCoin()
      @JvmName("setGasCoin")
      set(value) {
        _builder.setGasCoin(value)
      }
    /**
     * <code>.api_pb.Coin gas_coin = 9;</code>
     */
    fun clearGasCoin() {
      _builder.clearGasCoin()
    }
    /**
     * <code>.api_pb.Coin gas_coin = 9;</code>
     * @return Whether the gasCoin field is set.
     */
    fun hasGasCoin(): kotlin.Boolean {
      return _builder.hasGasCoin()
    }

    /**
     * <code>string type_hex = 17;</code>
     */
    var typeHex: kotlin.String
      @JvmName("getTypeHex")
      get() = _builder.getTypeHex()
      @JvmName("setTypeHex")
      set(value) {
        _builder.setTypeHex(value)
      }
    /**
     * <code>string type_hex = 17;</code>
     */
    fun clearTypeHex() {
      _builder.clearTypeHex()
    }

    /**
     * <pre>
     *    string type_name = 18;
     * </pre>
     *
     * <code>uint64 type = 10;</code>
     */
    var type: kotlin.Long
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <pre>
     *    string type_name = 18;
     * </pre>
     *
     * <code>uint64 type = 10;</code>
     */
    fun clearType() {
      _builder.clearType()
    }

    /**
     * <code>.google.protobuf.Any data = 11;</code>
     */
    var data: com.google.protobuf.Any
      @JvmName("getData")
      get() = _builder.getData()
      @JvmName("setData")
      set(value) {
        _builder.setData(value)
      }
    /**
     * <code>.google.protobuf.Any data = 11;</code>
     */
    fun clearData() {
      _builder.clearData()
    }
    /**
     * <code>.google.protobuf.Any data = 11;</code>
     * @return Whether the data field is set.
     */
    fun hasData(): kotlin.Boolean {
      return _builder.hasData()
    }

    /**
     * <code>bytes payload = 12;</code>
     */
    var payload: com.google.protobuf.ByteString
      @JvmName("getPayload")
      get() = _builder.getPayload()
      @JvmName("setPayload")
      set(value) {
        _builder.setPayload(value)
      }
    /**
     * <code>bytes payload = 12;</code>
     */
    fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * <code>bytes service_data = 16;</code>
     */
    var serviceData: com.google.protobuf.ByteString
      @JvmName("getServiceData")
      get() = _builder.getServiceData()
      @JvmName("setServiceData")
      set(value) {
        _builder.setServiceData(value)
      }
    /**
     * <code>bytes service_data = 16;</code>
     */
    fun clearServiceData() {
      _builder.clearServiceData()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>map&lt;string, string&gt; tags = 13;</code>
     */
     val tags: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getTagsMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.getTagsMap()
      )
    /**
     * <code>map&lt;string, string&gt; tags = 13;</code>
     */
    @JvmName("putTags")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TagsProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putTags(key, value)
       }
    /**
     * <code>map&lt;string, string&gt; tags = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setTags")
    inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TagsProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * <code>map&lt;string, string&gt; tags = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeTags")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TagsProxy>
      .remove(key: kotlin.String) {
         _builder.removeTags(key)
       }
    /**
     * <code>map&lt;string, string&gt; tags = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllTags")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TagsProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllTags(map)
       }
    /**
     * <code>map&lt;string, string&gt; tags = 13;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearTags")
    fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, TagsProxy>
      .clear() {
         _builder.clearTags()
       }

    /**
     * <code>uint64 code = 14;</code>
     */
    var code: kotlin.Long
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <code>uint64 code = 14;</code>
     */
    fun clearCode() {
      _builder.clearCode()
    }

    /**
     * <code>string log = 15;</code>
     */
    var log: kotlin.String
      @JvmName("getLog")
      get() = _builder.getLog()
      @JvmName("setLog")
      set(value) {
        _builder.setLog(value)
      }
    /**
     * <code>string log = 15;</code>
     */
    fun clearLog() {
      _builder.clearLog()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun counters.minter.grpc.client.TransactionResponse.copy(block: counters.minter.grpc.client.TransactionResponseKt.Dsl.() -> Unit): counters.minter.grpc.client.TransactionResponse =
  counters.minter.grpc.client.TransactionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
