//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package examples.api_pb2;

@kotlin.jvm.JvmSynthetic
public inline fun blockResponse(block: examples.api_pb2.BlockResponseKt.Dsl.() -> kotlin.Unit): examples.api_pb2.BlockResponse =
  examples.api_pb2.BlockResponseKt.Dsl._create(examples.api_pb2.BlockResponse.newBuilder()).apply { block() }._build()
public object BlockResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: examples.api_pb2.BlockResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: examples.api_pb2.BlockResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): examples.api_pb2.BlockResponse = _builder.build()

    /**
     * <code>string hash = 1 [json_name = "hash"];</code>
     */
    public var hash: kotlin.String
      @JvmName("getHash")
      get() = _builder.getHash()
      @JvmName("setHash")
      set(value) {
        _builder.setHash(value)
      }
    /**
     * <code>string hash = 1 [json_name = "hash"];</code>
     */
    public fun clearHash() {
      _builder.clearHash()
    }

    /**
     * <code>uint64 height = 2 [json_name = "height"];</code>
     */
    public var height: kotlin.Long
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <code>uint64 height = 2 [json_name = "height"];</code>
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }

    /**
     * <code>string time = 3 [json_name = "time"];</code>
     */
    public var time: kotlin.String
      @JvmName("getTime")
      get() = _builder.getTime()
      @JvmName("setTime")
      set(value) {
        _builder.setTime(value)
      }
    /**
     * <code>string time = 3 [json_name = "time"];</code>
     */
    public fun clearTime() {
      _builder.clearTime()
    }

    /**
     * <code>uint64 transaction_count = 4 [json_name = "transactionCount"];</code>
     */
    public var transactionCount: kotlin.Long
      @JvmName("getTransactionCount")
      get() = _builder.getTransactionCount()
      @JvmName("setTransactionCount")
      set(value) {
        _builder.setTransactionCount(value)
      }
    /**
     * <code>uint64 transaction_count = 4 [json_name = "transactionCount"];</code>
     */
    public fun clearTransactionCount() {
      _builder.clearTransactionCount()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TransactionsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     */
     public val transactions: com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTransactionsList()
      )
    /**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     * @param value The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTransactions")
    public fun com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>.add(value: examples.api_pb2.TransactionResponse) {
      _builder.addTransactions(value)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     * @param value The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTransactions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>.plusAssign(value: examples.api_pb2.TransactionResponse) {
      add(value)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     * @param values The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTransactions")
    public fun com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>.addAll(values: kotlin.collections.Iterable<examples.api_pb2.TransactionResponse>) {
      _builder.addAllTransactions(values)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     * @param values The transactions to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTransactions")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>.plusAssign(values: kotlin.collections.Iterable<examples.api_pb2.TransactionResponse>) {
      addAll(values)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     * @param index The index to set the value at.
     * @param value The transactions to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTransactions")
    public operator fun com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>.set(index: kotlin.Int, value: examples.api_pb2.TransactionResponse) {
      _builder.setTransactions(index, value)
    }/**
     * <code>repeated .api_pb.TransactionResponse transactions = 6 [json_name = "transactions"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTransactions")
    public fun com.google.protobuf.kotlin.DslList<examples.api_pb2.TransactionResponse, TransactionsProxy>.clear() {
      _builder.clearTransactions()
    }
    /**
     * <code>string block_reward = 7 [json_name = "blockReward"];</code>
     */
    public var blockReward: kotlin.String
      @JvmName("getBlockReward")
      get() = _builder.getBlockReward()
      @JvmName("setBlockReward")
      set(value) {
        _builder.setBlockReward(value)
      }
    /**
     * <code>string block_reward = 7 [json_name = "blockReward"];</code>
     */
    public fun clearBlockReward() {
      _builder.clearBlockReward()
    }

    /**
     * <code>uint64 size = 8 [json_name = "size"];</code>
     */
    public var size: kotlin.Long
      @JvmName("getSize")
      get() = _builder.getSize()
      @JvmName("setSize")
      set(value) {
        _builder.setSize(value)
      }
    /**
     * <code>uint64 size = 8 [json_name = "size"];</code>
     */
    public fun clearSize() {
      _builder.clearSize()
    }

    /**
     * <code>string proposer = 9 [json_name = "proposer"];</code>
     */
    public var proposer: kotlin.String
      @JvmName("getProposer")
      get() = _builder.getProposer()
      @JvmName("setProposer")
      set(value) {
        _builder.setProposer(value)
      }
    /**
     * <code>string proposer = 9 [json_name = "proposer"];</code>
     */
    public fun clearProposer() {
      _builder.clearProposer()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ValidatorsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     */
     public val validators: com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getValidatorsList()
      )
    /**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     * @param value The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addValidators")
    public fun com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>.add(value: examples.api_pb2.BlockResponse.Validator) {
      _builder.addValidators(value)
    }/**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     * @param value The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignValidators")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>.plusAssign(value: examples.api_pb2.BlockResponse.Validator) {
      add(value)
    }/**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     * @param values The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllValidators")
    public fun com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>.addAll(values: kotlin.collections.Iterable<examples.api_pb2.BlockResponse.Validator>) {
      _builder.addAllValidators(values)
    }/**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     * @param values The validators to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllValidators")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>.plusAssign(values: kotlin.collections.Iterable<examples.api_pb2.BlockResponse.Validator>) {
      addAll(values)
    }/**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     * @param index The index to set the value at.
     * @param value The validators to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setValidators")
    public operator fun com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>.set(index: kotlin.Int, value: examples.api_pb2.BlockResponse.Validator) {
      _builder.setValidators(index, value)
    }/**
     * <code>repeated .api_pb.BlockResponse.Validator validators = 10 [json_name = "validators"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearValidators")
    public fun com.google.protobuf.kotlin.DslList<examples.api_pb2.BlockResponse.Validator, ValidatorsProxy>.clear() {
      _builder.clearValidators()
    }
    /**
     * <code>.api_pb.BlockResponse.Evidence evidence = 13 [json_name = "evidence"];</code>
     */
    public var evidence: examples.api_pb2.BlockResponse.Evidence
      @JvmName("getEvidence")
      get() = _builder.getEvidence()
      @JvmName("setEvidence")
      set(value) {
        _builder.setEvidence(value)
      }
    /**
     * <code>.api_pb.BlockResponse.Evidence evidence = 13 [json_name = "evidence"];</code>
     */
    public fun clearEvidence() {
      _builder.clearEvidence()
    }
    /**
     * <code>.api_pb.BlockResponse.Evidence evidence = 13 [json_name = "evidence"];</code>
     * @return Whether the evidence field is set.
     */
    public fun hasEvidence(): kotlin.Boolean {
      return _builder.hasEvidence()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MissedProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     * @return A list containing the missed.
     */
    public val missed: com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMissedList()
      )
    /**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     * @param value The missed to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMissed")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>.add(value: kotlin.String) {
      _builder.addMissed(value)
    }
    /**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     * @param value The missed to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMissed")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     * @param values The missed to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMissed")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllMissed(values)
    }
    /**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     * @param values The missed to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMissed")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     * @param index The index to set the value at.
     * @param value The missed to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMissed")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setMissed(index, value)
    }/**
     * <code>repeated string missed = 12 [json_name = "missed"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMissed")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MissedProxy>.clear() {
      _builder.clearMissed()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EventsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     */
     public val events: com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEventsList()
      )
    /**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     * @param value The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEvents")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>.add(value: com.google.protobuf.Any) {
      _builder.addEvents(value)
    }/**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     * @param value The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEvents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>.plusAssign(value: com.google.protobuf.Any) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     * @param values The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEvents")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      _builder.addAllEvents(values)
    }/**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     * @param values The events to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEvents")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Any>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     * @param index The index to set the value at.
     * @param value The events to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEvents")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>.set(index: kotlin.Int, value: com.google.protobuf.Any) {
      _builder.setEvents(index, value)
    }/**
     * <code>repeated .google.protobuf.Any events = 14 [json_name = "events"];</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEvents")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Any, EventsProxy>.clear() {
      _builder.clearEvents()
    }}
  @kotlin.jvm.JvmSynthetic
  public inline fun validator(block: examples.api_pb2.BlockResponseKt.ValidatorKt.Dsl.() -> kotlin.Unit): examples.api_pb2.BlockResponse.Validator =
    examples.api_pb2.BlockResponseKt.ValidatorKt.Dsl._create(examples.api_pb2.BlockResponse.Validator.newBuilder()).apply { block() }._build()
  public object ValidatorKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: examples.api_pb2.BlockResponse.Validator.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: examples.api_pb2.BlockResponse.Validator.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): examples.api_pb2.BlockResponse.Validator = _builder.build()

      /**
       * <code>string public_key = 1 [json_name = "publicKey"];</code>
       */
      public var publicKey: kotlin.String
        @JvmName("getPublicKey")
        get() = _builder.getPublicKey()
        @JvmName("setPublicKey")
        set(value) {
          _builder.setPublicKey(value)
        }
      /**
       * <code>string public_key = 1 [json_name = "publicKey"];</code>
       */
      public fun clearPublicKey() {
        _builder.clearPublicKey()
      }

      /**
       * <code>bool signed = 2 [json_name = "signed"];</code>
       */
      public var signed: kotlin.Boolean
        @JvmName("getSigned")
        get() = _builder.getSigned()
        @JvmName("setSigned")
        set(value) {
          _builder.setSigned(value)
        }
      /**
       * <code>bool signed = 2 [json_name = "signed"];</code>
       */
      public fun clearSigned() {
        _builder.clearSigned()
      }
    }
  }
  @kotlin.jvm.JvmSynthetic
  public inline fun evidence(block: examples.api_pb2.BlockResponseKt.EvidenceKt.Dsl.() -> kotlin.Unit): examples.api_pb2.BlockResponse.Evidence =
    examples.api_pb2.BlockResponseKt.EvidenceKt.Dsl._create(examples.api_pb2.BlockResponse.Evidence.newBuilder()).apply { block() }._build()
  public object EvidenceKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: examples.api_pb2.BlockResponse.Evidence.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: examples.api_pb2.BlockResponse.Evidence.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): examples.api_pb2.BlockResponse.Evidence = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class EvidenceProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       */
       public val evidence: com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getEvidenceList()
        )
      /**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       * @param value The evidence to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addEvidence")
      public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>.add(value: com.google.protobuf.Struct) {
        _builder.addEvidence(value)
      }/**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       * @param value The evidence to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignEvidence")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>.plusAssign(value: com.google.protobuf.Struct) {
        add(value)
      }/**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       * @param values The evidence to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllEvidence")
      public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.Struct>) {
        _builder.addAllEvidence(values)
      }/**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       * @param values The evidence to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllEvidence")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.Struct>) {
        addAll(values)
      }/**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       * @param index The index to set the value at.
       * @param value The evidence to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setEvidence")
      public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>.set(index: kotlin.Int, value: com.google.protobuf.Struct) {
        _builder.setEvidence(index, value)
      }/**
       * <code>repeated .google.protobuf.Struct evidence = 1 [json_name = "evidence"];</code>
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearEvidence")
      public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.Struct, EvidenceProxy>.clear() {
        _builder.clearEvidence()
      }}
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.BlockResponse.copy(block: examples.api_pb2.BlockResponseKt.Dsl.() -> kotlin.Unit): examples.api_pb2.BlockResponse =
  examples.api_pb2.BlockResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.BlockResponse.Validator.copy(block: examples.api_pb2.BlockResponseKt.ValidatorKt.Dsl.() -> kotlin.Unit): examples.api_pb2.BlockResponse.Validator =
  examples.api_pb2.BlockResponseKt.ValidatorKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.BlockResponse.Evidence.copy(block: examples.api_pb2.BlockResponseKt.EvidenceKt.Dsl.() -> kotlin.Unit): examples.api_pb2.BlockResponse.Evidence =
  examples.api_pb2.BlockResponseKt.EvidenceKt.Dsl._create(this.toBuilder()).apply { block() }._build()
