//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package examples.api_pb2;

@kotlin.jvm.JvmSynthetic
public inline fun limitOrderRequest(block: examples.api_pb2.LimitOrderRequestKt.Dsl.() -> kotlin.Unit): examples.api_pb2.LimitOrderRequest =
  examples.api_pb2.LimitOrderRequestKt.Dsl._create(examples.api_pb2.LimitOrderRequest.newBuilder()).apply { block() }._build()
public object LimitOrderRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: examples.api_pb2.LimitOrderRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: examples.api_pb2.LimitOrderRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): examples.api_pb2.LimitOrderRequest = _builder.build()

    /**
     * <code>uint64 order_id = 1 [json_name = "orderId"];</code>
     */
    public var orderId: kotlin.Long
      @JvmName("getOrderId")
      get() = _builder.getOrderId()
      @JvmName("setOrderId")
      set(value) {
        _builder.setOrderId(value)
      }
    /**
     * <code>uint64 order_id = 1 [json_name = "orderId"];</code>
     */
    public fun clearOrderId() {
      _builder.clearOrderId()
    }

    /**
     * <code>uint64 height = 2 [json_name = "height"];</code>
     */
    public var height: kotlin.Long
      @JvmName("getHeight")
      get() = _builder.getHeight()
      @JvmName("setHeight")
      set(value) {
        _builder.setHeight(value)
      }
    /**
     * <code>uint64 height = 2 [json_name = "height"];</code>
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.LimitOrderRequest.copy(block: examples.api_pb2.LimitOrderRequestKt.Dsl.() -> kotlin.Unit): examples.api_pb2.LimitOrderRequest =
  examples.api_pb2.LimitOrderRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
