//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package examples.api_pb2;

@kotlin.jvm.JvmSynthetic
public inline fun nodeInfo(block: examples.api_pb2.NodeInfoKt.Dsl.() -> kotlin.Unit): examples.api_pb2.NodeInfo =
  examples.api_pb2.NodeInfoKt.Dsl._create(examples.api_pb2.NodeInfo.newBuilder()).apply { block() }._build()
public object NodeInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: examples.api_pb2.NodeInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: examples.api_pb2.NodeInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): examples.api_pb2.NodeInfo = _builder.build()

    /**
     * <code>.api_pb.NodeInfo.ProtocolVersion protocol_version = 8 [json_name = "protocolVersion"];</code>
     */
    public var protocolVersion: examples.api_pb2.NodeInfo.ProtocolVersion
      @JvmName("getProtocolVersion")
      get() = _builder.getProtocolVersion()
      @JvmName("setProtocolVersion")
      set(value) {
        _builder.setProtocolVersion(value)
      }
    /**
     * <code>.api_pb.NodeInfo.ProtocolVersion protocol_version = 8 [json_name = "protocolVersion"];</code>
     */
    public fun clearProtocolVersion() {
      _builder.clearProtocolVersion()
    }
    /**
     * <code>.api_pb.NodeInfo.ProtocolVersion protocol_version = 8 [json_name = "protocolVersion"];</code>
     * @return Whether the protocolVersion field is set.
     */
    public fun hasProtocolVersion(): kotlin.Boolean {
      return _builder.hasProtocolVersion()
    }

    /**
     * <code>string id = 1 [json_name = "id"];</code>
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>string listen_addr = 2 [json_name = "listenAddr"];</code>
     */
    public var listenAddr: kotlin.String
      @JvmName("getListenAddr")
      get() = _builder.getListenAddr()
      @JvmName("setListenAddr")
      set(value) {
        _builder.setListenAddr(value)
      }
    /**
     * <code>string listen_addr = 2 [json_name = "listenAddr"];</code>
     */
    public fun clearListenAddr() {
      _builder.clearListenAddr()
    }

    /**
     * <code>string network = 3 [json_name = "network"];</code>
     */
    public var network: kotlin.String
      @JvmName("getNetwork")
      get() = _builder.getNetwork()
      @JvmName("setNetwork")
      set(value) {
        _builder.setNetwork(value)
      }
    /**
     * <code>string network = 3 [json_name = "network"];</code>
     */
    public fun clearNetwork() {
      _builder.clearNetwork()
    }

    /**
     * <code>string version = 4 [json_name = "version"];</code>
     */
    public var version: kotlin.String
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * <code>string version = 4 [json_name = "version"];</code>
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * <code>string channels = 5 [json_name = "channels"];</code>
     */
    public var channels: kotlin.String
      @JvmName("getChannels")
      get() = _builder.getChannels()
      @JvmName("setChannels")
      set(value) {
        _builder.setChannels(value)
      }
    /**
     * <code>string channels = 5 [json_name = "channels"];</code>
     */
    public fun clearChannels() {
      _builder.clearChannels()
    }

    /**
     * <code>string moniker = 6 [json_name = "moniker"];</code>
     */
    public var moniker: kotlin.String
      @JvmName("getMoniker")
      get() = _builder.getMoniker()
      @JvmName("setMoniker")
      set(value) {
        _builder.setMoniker(value)
      }
    /**
     * <code>string moniker = 6 [json_name = "moniker"];</code>
     */
    public fun clearMoniker() {
      _builder.clearMoniker()
    }

    /**
     * <code>.api_pb.NodeInfo.Other other = 7 [json_name = "other"];</code>
     */
    public var other: examples.api_pb2.NodeInfo.Other
      @JvmName("getOther")
      get() = _builder.getOther()
      @JvmName("setOther")
      set(value) {
        _builder.setOther(value)
      }
    /**
     * <code>.api_pb.NodeInfo.Other other = 7 [json_name = "other"];</code>
     */
    public fun clearOther() {
      _builder.clearOther()
    }
    /**
     * <code>.api_pb.NodeInfo.Other other = 7 [json_name = "other"];</code>
     * @return Whether the other field is set.
     */
    public fun hasOther(): kotlin.Boolean {
      return _builder.hasOther()
    }
  }
  @kotlin.jvm.JvmSynthetic
  public inline fun protocolVersion(block: examples.api_pb2.NodeInfoKt.ProtocolVersionKt.Dsl.() -> kotlin.Unit): examples.api_pb2.NodeInfo.ProtocolVersion =
    examples.api_pb2.NodeInfoKt.ProtocolVersionKt.Dsl._create(examples.api_pb2.NodeInfo.ProtocolVersion.newBuilder()).apply { block() }._build()
  public object ProtocolVersionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: examples.api_pb2.NodeInfo.ProtocolVersion.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: examples.api_pb2.NodeInfo.ProtocolVersion.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): examples.api_pb2.NodeInfo.ProtocolVersion = _builder.build()

      /**
       * <code>uint64 p2p = 3 [json_name = "p2p"];</code>
       */
      public var p2P: kotlin.Long
        @JvmName("getP2P")
        get() = _builder.getP2P()
        @JvmName("setP2P")
        set(value) {
          _builder.setP2P(value)
        }
      /**
       * <code>uint64 p2p = 3 [json_name = "p2p"];</code>
       */
      public fun clearP2P() {
        _builder.clearP2P()
      }

      /**
       * <code>uint64 block = 1 [json_name = "block"];</code>
       */
      public var block: kotlin.Long
        @JvmName("getBlock")
        get() = _builder.getBlock()
        @JvmName("setBlock")
        set(value) {
          _builder.setBlock(value)
        }
      /**
       * <code>uint64 block = 1 [json_name = "block"];</code>
       */
      public fun clearBlock() {
        _builder.clearBlock()
      }

      /**
       * <code>uint64 app = 2 [json_name = "app"];</code>
       */
      public var app: kotlin.Long
        @JvmName("getApp")
        get() = _builder.getApp()
        @JvmName("setApp")
        set(value) {
          _builder.setApp(value)
        }
      /**
       * <code>uint64 app = 2 [json_name = "app"];</code>
       */
      public fun clearApp() {
        _builder.clearApp()
      }
    }
  }
  @kotlin.jvm.JvmSynthetic
  public inline fun other(block: examples.api_pb2.NodeInfoKt.OtherKt.Dsl.() -> kotlin.Unit): examples.api_pb2.NodeInfo.Other =
    examples.api_pb2.NodeInfoKt.OtherKt.Dsl._create(examples.api_pb2.NodeInfo.Other.newBuilder()).apply { block() }._build()
  public object OtherKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: examples.api_pb2.NodeInfo.Other.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: examples.api_pb2.NodeInfo.Other.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): examples.api_pb2.NodeInfo.Other = _builder.build()

      /**
       * <code>string tx_index = 2 [json_name = "txIndex"];</code>
       */
      public var txIndex: kotlin.String
        @JvmName("getTxIndex")
        get() = _builder.getTxIndex()
        @JvmName("setTxIndex")
        set(value) {
          _builder.setTxIndex(value)
        }
      /**
       * <code>string tx_index = 2 [json_name = "txIndex"];</code>
       */
      public fun clearTxIndex() {
        _builder.clearTxIndex()
      }

      /**
       * <code>string rpc_address = 1 [json_name = "rpcAddress"];</code>
       */
      public var rpcAddress: kotlin.String
        @JvmName("getRpcAddress")
        get() = _builder.getRpcAddress()
        @JvmName("setRpcAddress")
        set(value) {
          _builder.setRpcAddress(value)
        }
      /**
       * <code>string rpc_address = 1 [json_name = "rpcAddress"];</code>
       */
      public fun clearRpcAddress() {
        _builder.clearRpcAddress()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.NodeInfo.copy(block: examples.api_pb2.NodeInfoKt.Dsl.() -> kotlin.Unit): examples.api_pb2.NodeInfo =
  examples.api_pb2.NodeInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.NodeInfo.ProtocolVersion.copy(block: examples.api_pb2.NodeInfoKt.ProtocolVersionKt.Dsl.() -> kotlin.Unit): examples.api_pb2.NodeInfo.ProtocolVersion =
  examples.api_pb2.NodeInfoKt.ProtocolVersionKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.NodeInfo.Other.copy(block: examples.api_pb2.NodeInfoKt.OtherKt.Dsl.() -> kotlin.Unit): examples.api_pb2.NodeInfo.Other =
  examples.api_pb2.NodeInfoKt.OtherKt.Dsl._create(this.toBuilder()).apply { block() }._build()
