//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: events.proto

package examples.api_pb2;

@kotlin.jvm.JvmSynthetic
public inline fun updateNetworkEvent(block: examples.api_pb2.UpdateNetworkEventKt.Dsl.() -> kotlin.Unit): examples.api_pb2.UpdateNetworkEvent =
  examples.api_pb2.UpdateNetworkEventKt.Dsl._create(examples.api_pb2.UpdateNetworkEvent.newBuilder()).apply { block() }._build()
public object UpdateNetworkEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: examples.api_pb2.UpdateNetworkEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: examples.api_pb2.UpdateNetworkEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): examples.api_pb2.UpdateNetworkEvent = _builder.build()

    /**
     * <code>string version = 1 [json_name = "version"];</code>
     */
    public var version: kotlin.String
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * <code>string version = 1 [json_name = "version"];</code>
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun examples.api_pb2.UpdateNetworkEvent.copy(block: examples.api_pb2.UpdateNetworkEventKt.Dsl.() -> kotlin.Unit): examples.api_pb2.UpdateNetworkEvent =
  examples.api_pb2.UpdateNetworkEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()
