// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package examples.api_pb2;

public interface BlocksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.BlocksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api_pb.BlockResponse blocks = 1 [json_name = "blocks"];</code>
   */
  java.util.List<examples.api_pb2.BlockResponse> 
      getBlocksList();
  /**
   * <code>repeated .api_pb.BlockResponse blocks = 1 [json_name = "blocks"];</code>
   */
  examples.api_pb2.BlockResponse getBlocks(int index);
  /**
   * <code>repeated .api_pb.BlockResponse blocks = 1 [json_name = "blocks"];</code>
   */
  int getBlocksCount();
  /**
   * <code>repeated .api_pb.BlockResponse blocks = 1 [json_name = "blocks"];</code>
   */
  java.util.List<? extends examples.api_pb2.BlockResponseOrBuilder> 
      getBlocksOrBuilderList();
  /**
   * <code>repeated .api_pb.BlockResponse blocks = 1 [json_name = "blocks"];</code>
   */
  examples.api_pb2.BlockResponseOrBuilder getBlocksOrBuilder(
      int index);
}
