// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package examples.api_pb2;

public interface CandidatesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.CandidatesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.api_pb.CandidatesRequest.CandidateStatus status = 3 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.api_pb.CandidatesRequest.CandidateStatus status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  examples.api_pb2.CandidatesRequest.CandidateStatus getStatus();
}
