// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package examples.api_pb2;

public interface EditCandidateCommissionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.EditCandidateCommission)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pub_key = 1 [json_name = "pubKey"];</code>
   * @return The pubKey.
   */
  java.lang.String getPubKey();
  /**
   * <code>string pub_key = 1 [json_name = "pubKey"];</code>
   * @return The bytes for pubKey.
   */
  com.google.protobuf.ByteString
      getPubKeyBytes();

  /**
   * <code>uint64 commission = 2 [json_name = "commission"];</code>
   * @return The commission.
   */
  long getCommission();
}
