// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources.proto

package examples.api_pb2;

public interface MinGasPriceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.MinGasPriceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 min_gas_price = 3 [json_name = "minGasPrice"];</code>
   * @return The minGasPrice.
   */
  long getMinGasPrice();
}
