// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package examples.api_pb2;

public interface RemoveCandidateEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.RemoveCandidateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string candidate_pub_key = 1 [json_name = "candidatePubKey"];</code>
   * @return The candidatePubKey.
   */
  java.lang.String getCandidatePubKey();
  /**
   * <code>string candidate_pub_key = 1 [json_name = "candidatePubKey"];</code>
   * @return The bytes for candidatePubKey.
   */
  com.google.protobuf.ByteString
      getCandidatePubKeyBytes();
}
