// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package examples.api_pb2;

public interface SetCandidateOnDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.SetCandidateOnData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pub_key = 1 [json_name = "pubKey"];</code>
   * @return The pubKey.
   */
  java.lang.String getPubKey();
  /**
   * <code>string pub_key = 1 [json_name = "pubKey"];</code>
   * @return The bytes for pubKey.
   */
  com.google.protobuf.ByteString
      getPubKeyBytes();
}
