// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package examples.api_pb2;

public interface UnbondDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api_pb.UnbondData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pub_key = 1 [json_name = "pubKey"];</code>
   * @return The pubKey.
   */
  java.lang.String getPubKey();
  /**
   * <code>string pub_key = 1 [json_name = "pubKey"];</code>
   * @return The bytes for pubKey.
   */
  com.google.protobuf.ByteString
      getPubKeyBytes();

  /**
   * <code>.api_pb.Coin coin = 2 [json_name = "coin"];</code>
   * @return Whether the coin field is set.
   */
  boolean hasCoin();
  /**
   * <code>.api_pb.Coin coin = 2 [json_name = "coin"];</code>
   * @return The coin.
   */
  examples.api_pb2.Coin getCoin();
  /**
   * <code>.api_pb.Coin coin = 2 [json_name = "coin"];</code>
   */
  examples.api_pb2.CoinOrBuilder getCoinOrBuilder();

  /**
   * <code>string value = 3 [json_name = "value"];</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 3 [json_name = "value"];</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
