//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: data.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
public inline fun editCoinOwnerData(block: counters.minter.grpc.client.EditCoinOwnerDataKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.EditCoinOwnerData =
  counters.minter.grpc.client.EditCoinOwnerDataKt.Dsl._create(counters.minter.grpc.client.EditCoinOwnerData.newBuilder()).apply { block() }._build()
public object EditCoinOwnerDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: counters.minter.grpc.client.EditCoinOwnerData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.EditCoinOwnerData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.EditCoinOwnerData = _builder.build()

    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     */
    public var symbol: kotlin.String
      @JvmName("getSymbol")
      get() = _builder.getSymbol()
      @JvmName("setSymbol")
      set(value) {
        _builder.setSymbol(value)
      }
    /**
     * <code>string symbol = 1 [json_name = "symbol"];</code>
     */
    public fun clearSymbol() {
      _builder.clearSymbol()
    }

    /**
     * <code>string new_owner = 2 [json_name = "newOwner"];</code>
     */
    public var newOwner: kotlin.String
      @JvmName("getNewOwner")
      get() = _builder.getNewOwner()
      @JvmName("setNewOwner")
      set(value) {
        _builder.setNewOwner(value)
      }
    /**
     * <code>string new_owner = 2 [json_name = "newOwner"];</code>
     */
    public fun clearNewOwner() {
      _builder.clearNewOwner()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun counters.minter.grpc.client.EditCoinOwnerData.copy(block: counters.minter.grpc.client.EditCoinOwnerDataKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.EditCoinOwnerData =
  counters.minter.grpc.client.EditCoinOwnerDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()
