//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resources.proto

package counters.minter.grpc.client;

@kotlin.jvm.JvmSynthetic
public inline fun estimateTxCommissionRequest(block: counters.minter.grpc.client.EstimateTxCommissionRequestKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.EstimateTxCommissionRequest =
  counters.minter.grpc.client.EstimateTxCommissionRequestKt.Dsl._create(counters.minter.grpc.client.EstimateTxCommissionRequest.newBuilder()).apply { block() }._build()
public object EstimateTxCommissionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: counters.minter.grpc.client.EstimateTxCommissionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: counters.minter.grpc.client.EstimateTxCommissionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): counters.minter.grpc.client.EstimateTxCommissionRequest = _builder.build()

    /**
     * <pre>
     *    uint64 height = 2 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
     *        type: INTEGER
     *    }];
     * </pre>
     *
     * <code>string tx = 1 [json_name = "tx"];</code>
     */
    public var tx: kotlin.String
      @JvmName("getTx")
      get() = _builder.getTx()
      @JvmName("setTx")
      set(value) {
        _builder.setTx(value)
      }
    /**
     * <pre>
     *    uint64 height = 2 [(grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
     *        type: INTEGER
     *    }];
     * </pre>
     *
     * <code>string tx = 1 [json_name = "tx"];</code>
     */
    public fun clearTx() {
      _builder.clearTx()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun counters.minter.grpc.client.EstimateTxCommissionRequest.copy(block: counters.minter.grpc.client.EstimateTxCommissionRequestKt.Dsl.() -> kotlin.Unit): counters.minter.grpc.client.EstimateTxCommissionRequest =
  counters.minter.grpc.client.EstimateTxCommissionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
